runnerTag: latest

# Needs to define name, description
include "ocibuild.project.conf"
# Needs to define team, phoneBookId, authCompartmentOcid
include "ocibuild.team.conf"
# Needs to define releaseRepository, developmentRepository
include "ocibuild.repos.conf"
# If exists, should define sendNotificationBranches, slackChannels
include "ocibuild.slack.conf"

majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
version: ${shortversion}.${BLD_NUMBER} # ${?BLD_BRANCH_SUFFIX}
triggerOnCommitBranches: ["master", "main", "pull-requests", "develop"]
releaseBranches: ["master", "main", "develop"]
steps: [
    {
      name: packagewheel
      type: python
      pyVersion: 3.11
      runnerImage: build-runner-python-ol8
      environment: {
        RELEASE_VERSION: ${shortversion},
        RELEASE_REPOSITORY: ${releaseRepository},
        DEVELOP_REPOSITORY: ${developmentRepository},
      },
      pythonCommands: [
        { args: "python-build-system.py" },
      ]
      artifacts: [
        "ocibuild.*.conf",  # We have to ask for these explicitly
        "dist/*.*",
        ${releaseRepository}"/*.*",
        ${developmentRepository}"/*.*"
      ]
      skipOnDryRun: false
      inputType: source
    },
    {
      name: publish_release
      type: publishgeneric
      repository: ${releaseRepository}
      dependsOn: packagewheel
      filePathsToPublish: [
        { localFile: ${releaseRepository}"/*.whl", targetDir: "/" },
        { localFile: ${releaseRepository}"/*.tar.gz", targetDir: "/" }
      ]
    },
    {
      name: publish_develop
      type: publishgeneric
      repository: ${developmentRepository}
      dependsOn: packagewheel
      filePathsToPublish: [
        { localFile: ${developmentRepository}"/*.whl", targetDir: "/" },
        { localFile: ${developmentRepository}"/*.tar.gz", targetDir: "/" }
      ]
    },
    {
      name: publish_default
      type: publishgeneric
      repository: ${releaseRepository}
      dependsOn: packagewheel
      filePathsToPublish: [
        { localFile: "dist/*.whl", targetDir: "/" },
        { localFile: "dist/*.tar.gz", targetDir: "/" }
      ]
    }
]
