runnerTag: latest

# Needs to define name, description
name: dynamic-agent-runner
description: A Python library for running agent workflows from agent-design artifacts.
# Needs to define team, phoneBookId, authCompartmentOcid
team: INDCON
phoneBookId: individual-contributors
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaalt3ghoq5nfxenlijgbauts66jr6ntlctdvkp7n34pruewyb3vi4q
# Needs to define releaseRepository, developmentRepository
releaseRepository: indcon-release-pypi-local
developmentRepository: indcon-dev-pypi-local
# If exists, should define sendNotificationBranches, slackChannels
sendNotificationBranches: []
slackChannels: []

majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
version: ${shortversion}.${BLD_NUMBER} # ${?BLD_BRANCH_SUFFIX}
triggerOnCommitBranches: ["master", "main", "pull-requests", "develop"]
triggerBuildChangePaths: [
    "./ocibuild.conf",
    "./ocibuild.project.conf",
    "./ocibuild.repos.conf",
    "./ocibuild.team.conf",
    "./ocibuild.slack.conf",
    "./poetry.lock",
    "./pyproject.toml",
    "./python-build-system.py",
    "./vendor/wheels/litellm-1.92.0-py3-none-any.whl",
    "src/",
    "src/dynamic_agent_runner/"
]
releaseBranches: ["master", "main", "develop"]
steps: [
    {
      name: packagewheel
      type: python
      pyVersion: 3.11
      runnerImage: build-runner-python-ol8
      environment: {
        RELEASE_VERSION: ${shortversion},
        RELEASE_REPOSITORY: ${releaseRepository},
        DEVELOP_REPOSITORY: ${developmentRepository},
      },
      pythonCommands: [
        { args: "python-build-system.py" },
      ]
      artifacts: [
        "ocibuild.*.conf",  # We have to ask for these explicitly
        "dist/*.*",
        ${releaseRepository}"/*.*",
        ${developmentRepository}"/*.*"
      ]
      skipOnDryRun: false
      inputType: source
    },
    {
      name: publish_release
      type: publishgeneric
      repository: ${releaseRepository}
      dependsOn: packagewheel
      filePathsToPublish: [
        { localFile: ${releaseRepository}"/*.whl", targetDir: "/" },
        { localFile: ${releaseRepository}"/*.tar.gz", targetDir: "/" }
      ]
    },
    {
      name: publish_develop
      type: publishgeneric
      repository: ${developmentRepository}
      dependsOn: packagewheel
      filePathsToPublish: [
        { localFile: ${developmentRepository}"/*.whl", targetDir: "/" },
        { localFile: ${developmentRepository}"/*.tar.gz", targetDir: "/" }
      ]
    },
    {
      name: publish_default
      type: publishgeneric
      repository: ${releaseRepository}
      dependsOn: packagewheel
      filePathsToPublish: [
        { localFile: "dist/*.whl", targetDir: "/" },
        { localFile: "dist/*.tar.gz", targetDir: "/" }
      ]
    }
]
