[project]
name = "dynamic-agent-runner"
version = "0.1.0"
description = ""
authors = [
    {name = "Bob Schumaker",email = "bob.schumaker@oracle.com"}
]
dynamic = ["dependencies", "requires-python"]

[tool.poetry]
packages = [
    { include = "dynamic_agent_runner", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
docopt-ng = ">=0.9.0"
roschumalib = {version = "^0.3.386", extras = ["application", "graphics", "spreadsheets"]}
openai = "^2.38.0"
PyYAML = ">=6.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
icecream = "*"
pipdeptree = "*"
tqdm = ">=4.66"
ruff = "^0.15.10"
pre-commit = "^4.5.1"
isort = "^8.0.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinxcontrib-confluencebuilder = "*"
myst-parser = "*"

[tool.poetry.group.test.dependencies]
pytest-cov = "^7.1.0"
pytest-parallel = "^0.1.1"

[[tool.poetry.source]]
name = 'global-release-pypi'
url = 'https://artifactory.oci.oraclecorp.com/api/pypi/global-release-pypi/simple'
priority = "primary"

[[tool.poetry.source]]
name = 'global-dev-pypi'
url = 'https://artifactory.oci.oraclecorp.com/api/pypi/global-dev-pypi/simple'
priority = "supplemental"

[tool.pyright.defineConstant]
PYQT5 = false
PYSIDE2 = false
PYQT6 = false
PYSIDE6 = true

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["B", "C", "E", "F", "W"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint.isort]
split-on-trailing-comma = true
